apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - githubcred.yaml
    #- container-image.yaml
    #resources:
    #- buildcontainerimage.yaml
namespace: workflows

