apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: workflows
  name: build-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
