---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: testing
  source:
    repoURL: https://github.com/ApdexOne/infra-base.git
    targetRevision: HEAD
    path: infra/argo-combined-demo/testing
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
