apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-workflows
  namespace: argo
spec:
  rules:
  - http:
      paths:
        - backend:
            serviceName: argo-server
            servicePort: 2746
          path: /
    host: argo-workflows.127.0.0.1.nip.io

