apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAH7KPcjb4beC8Np5Id7C91YtI2bLQY2cfS0myawKRsrs67diOnuxxJqIsBWEESmQXqoRHY/VDnw9z3s10A5KfCHDeYUEzHYg1kes8We0rCguBRurULzrph+lMnDONIiH3ngA7VWeUiY3w/oM55cexdJ8HRwPf7g/cVJhUxQvY7BV5k/oQM4qBMY1elr1mJPZiUl4nR9Lyru0jL63QIjQ/f7k7Gqxpjmslx0PFcPB8vcWbbOaZyHO6kJzgWhw5rTO09GaYjCnsFUY55OBvlHC5rkEOjo+z/jqDKTbqWETiM1Ifl9OAro4g5j90c3bNBt3jg4uLUfsQYdAlM68Gb3rbMNmwb0MfUdnv+jvVbPnaJKH8qKVn00wRLeJpC/DEpRlN0pEysWW6EbrMwxu2Kwjt3vVpj0vrHRBFCPQWKIRA9Sg17OHWwB3sVzjaZg+0LOEmajLSaA/UoAtJSv1bTfOdqpsfoVDVo9dJtxmi6Ci/n1RsAmrCCmiP5cUT8S1QwsgoBi2KAyswNGjGlhNxHlVQCX7khYmbg9c8hnR2vlh9G8Uzot/atKEWWFsjg/sXrT/qAnGrdJaXzRfIAz3rs823990KaleTeqkJSr/+nV/Vwc04DB7ybXPh3Lq0Ws2dOqzUM6QGC6jkiFBVfEPeignuXP7ZK94a7PFW3tilmD7B75x7/gmULYU/ZefkzBkdnm/EgOiBDqeOx+fLM2GO0aCPwtGbv2MtI6sD7EGgMDUFZjAXz3J7yx+rwPCWgR1z/Ju0YUSbKTJHA4OsPnFYyHvaHAF35oIVnfRnT++DS/fPFDpJh6I+1l6+INoRHOZcuGR2kFhASsKcnghgprXufaLADyOOK++5XuaJ7PfrnMfO//f4YSmOsobIB89OXuf83o1Qi4hKzrpBQgD0W9L25GJHDfTtr4J9Mh9CNJExfeRtLnSP5aXsjLihjR6LE/YGMkL94olI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

