apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
  generateName: pull-build-test-
  namespace: argo
spec:
  serviceAccountName: workflow
  entrypoint: run-e2e-tests
  arguments:
    parameters:
      - name: repo
        value: "git@gitea-ssh.services.svc:norge/pipeline-demo-test.git"
      - name: revision
        value: "HEAD"
  volumes:
  - name: regcred
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
    - name: run-e2e-tests
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
              repo: git@gitea-ssh.services.svc:norge/pipeline-demo-test.git
              revision: "HEAD"
              insecureIgnoreHostKey: true
              usernameSecret:
                name: github-access-ssh
                key: username
              passwordSecret:
                name: github-access-ssh
                key: password
              sshPrivateKeySecret:
                name: github-access-ssh
                key: sshPrivateKey
      script:
        image: cypress/included:3.4.0
        command: [bash]
        source: |
          yarn install
          npm run runHeadless
        workingDir: /src
