apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
  generateName: pull-build-test-
  namespace: argo
spec:
  serviceAccountName: workflow
  entrypoint: run-e2e-tests
  arguments:
    parameters:
      - name: repo
        value: "git@gitea-ssh.services.svc:norge/pipeline-demo-test.git"
      - name: revision
        value: "HEAD"
  volumes:
  - name: regcred
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
    - name: run-e2e-tests
      dag:
        tasks:
          - name: run-cypress
            templateRef:
              name: cypress-test
              template: run-e2e-tests
              clusterScope: true
            arguments:
              parameters:
                - name: repository
                  value: git@gitea-ssh.services.svc:norge/pipeline-demo-test.git
                - name: branch
                  value: master
