apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
  generateName: pull-build-test-
  namespace: argo
spec:
  serviceAccountName: workflow
  entrypoint: checkout
  arguments:
    parameters:
      - name: repo
        value: "git@gitea-ssh.services.svc:ApdexOne/pipeline-demo.git"
      - name: revision
        value: "HEAD"
  volumes:
  - name: regcred
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
    - name: checkout
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
              repo: git@gitea-ssh.services.svc:ApdexOne/pipeline-demo.git
              revision: "HEAD"
              usernameSecret:
                name: github-access-ssh
                key: username
              passwordSecret:
                name: github-access-ssh
                key: password
              sshPrivateKeySecret:
                name: github-access-ssh
                key: sshPrivateKey
      container:
        image: golang:1.10
        command: ["/bin/sh","-c"]
        args: ["cd /src && git status && ls -l"]
        workingDir: /src
