apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
  generateName: pull-build-test-
  namespace: argo
spec:
  entrypoint: diamond
  templates:
    - name: diamond
      dag:
        tasks:
          - name: e2e-tests
            arguments:
              parameters:
                - name: repository
                  value: "git@gitea-ssh.services.svc:norge/pipeline-demo-test.git"
                - name: brach
                  value: "master"
            workflowTemplateRef:
              name: cypress-test
              template: run-tests
              clusterScope: true
