apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
  generateName: pull-build-test-
  namespace: workflow
spec:
  serviceAccountName: workflow
  entrypoint: run-tests
  arguments:
    parameters:
      - name: repository
        value: "git@gitea-ssh.services.svc:norge/pipeline-demo-test.git"
      - name: brach
        value: "master"
  workflowTemplateRef:
    name: cypress-test
    clusterScope: true
