apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: testing
  source:
    path: infra/k8s-apps/testing
    repoURL: git@github.com:ApdexOne/base-project.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

