---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: testing
  source:
    repoURL: http://gitea-http.services.svc:3000/ApdexOne/platform.git
    targetRevision: HEAD
    path: infra/testing
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
