apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: testing
  source:
    path: infra/argo-combined-demo/gitea
    repoURL: http://git.127.0.0.1.nip.io/ApdexOne/platform.git
    targetRevision: HEAD
  destination:
    namespace: git
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
