apiVersion: v1
data:
  admin.password: JDJhJDEwJE5jQlYzNDZzekl4QUFSaXREdHIyQy41c1pPLlpzWFd4cE8vTHE5QWgwWnlGNUFxSFpUOWd1
  admin.passwordMtime: MjAyMi0wMi0xM1QxMjo1MDo0MFo=
  server.secretkey: bytkcXM0b1VjS25UM1dsdDJUSDhvc1VmM0wvU25yRzV1Vzk0aDZjdDVBRT0=
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
