---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitea
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    project1:
      port: "12000"
      endpoint: /project1
      method: POST
    cronjob:
      port: "12000"
      endpoint: /cronjob
      method: POST

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: gitea-eventsource-svc
           port:
             number: 12000
    host: webhook.127.0.0.1.nip.io
