apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAadQL8xoVG4AiJ+3S2LUdp14ChN1+B6Hj6VcUShQ0Zm2bBWytfyWAvrTrjK7Gqtfs1obQ05UkT9Cc75NaYyRQyyyNq88BkKJYWt+Tn1TtHPZAefaGDgvYQ3e5qGQMpX5OZaQKod2or2kM8WezQ4KDEpaVI9hcriHDnRdQCQNkf9WAKJ+ecgNxtKWSgA1+D53/Hl9A7ZROwPMnTnj7mPAXtJUErRs1sVroWZXH9jmLmg4D3shWlOTMP/uKePeiFZoJn3Tyfwta9IlpTRdUcwrvM4YnPoCmE2GQdmgshUOxtmNsIoKThbUlr1xKhgOAzvxkU4UDEgleHpmRYu6uHHHxVpOzfHHQskk1uJxjK12QWYmCt7pwE3zLYqy8tp/ZZyhogqeOisBVS1cl7dVuBpIDoykSqIUl/xwZZKw12L4QSq1GNe/uuFWfXG/JfhutyTC9EMJ+GePX6OtVzO+Q3+h4fWfgkrNgZ7IiRaabhI26iYhxRZU62XORN1dg+25sHWHaDADWOX8UBG5F9kr8RUneP91w2uMf283JwJl2dY8kTE9V040Pc2ybeOuBYVY8wURYwxistWlM4wckMFY+t3sRWEm+s4bAhXa+oxKtYhbu0N/H5xafOM6raR0Ik/LlsYsUzlia03Z4DaHoKpQH770Tn5MC3vIKxRrK0K5GpEYcPm6+Q4seHp7b+cMNDsaWuKYmXuQPreu3fZXGcU2cHRo87GStnSPIUwDU/cgBf323LhyjuvKSHvdnG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

