apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBW4+9I10hpdh5mTMOIsnP/EOJFcc10AW6cR57hNb6HapALgkdu3BQAyxy4xc6lk0C9fyMfrR1cOcGZXzW6G6AfyPzGmQxvtJiqHz8gstmTKFtP7QMCMtXDBv+C47TkbVq4SXGb5pjC+vTLC+9xBq8U521QczA96vmY+WqcgClYwSAUZhqV/zWGRsSaF8Bnrbq+xFHBnCSsiuOLz/0la0MsfvROpKkwJi7vwKkRD3UV/UMEgs6pa87OrNKx6H/sykIf25OWyDqoig7u+AjG1VzFcawp6HDRfWrAEzQtV/sqjti9cxTRgTAJZbrb1MeFFjozmZsb+FsR+zbcP1gXvK4NuKYqnAGflDCTixzr+IStSNoXsLzbg7an/igUTrralFgqhB2yzC63BO534tQ5oylf5tNOBNU8555ICwKiYwMXUHX7UYE8p6q2Q+yO+u3nwtmyGMASk/NdjFQodYj7HmPar95SiHmdBoCE82FHcFdHWmW+BczHkXyGBGy1Qflik3BCpat7xss9uw1Vew+i2BN4iL+/ghrE82s7CWO3BHEeh+10RTKnO0GOTU7uUuA6jPRrqVYUYmg0lgDL4MAl3ckaEI/uSRbCF+cFcXd8wCNS8CKtLL3Qqp2D0W+c04sWnbTeHN9TeDm83ZV2DdX5Dwl5zS23sLmn1prPLyTN1qKrOEEtlfjoLV20dJbBSVAR9KabV2iDp/gdYVWkiZWyrmlSArRDsHbDOWMclCzdSKV+DILsQ2It1Wjq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

