apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBm1Gz8pjw2xaB0GUa8+NZdfSoJ+FVVfZp6woctwV5y1yuA7K7TA+RrK1e4Dn7CPPZxSoRZS0F6M6nmE6VB5niMzUYHGMMvluMjmtdGk0QdUowm5k83VjydJdrNMkTA9tg+11OL1OXr36pyx4jCS2nMklm4ymRVbECnmblppskSqQJgmGc/Ae3Vg0LPHxqU3bqX1NR1scO9j5GV93WbAR+YStul86DYoPwHgrYErNUJRkHa9L9elc/VQk1Kh0FHaeYIZMvF7s3LaoBPiVkrHIefSUadq011huOiwnj7mpjzrIUDS7Oj624jCFg66lxbZgJBDolN0H8aikDgTPaoZx5r5moOhVVLHEpJ/meF2y8Gyan6D7MDKD+Kfq8V3ex8y4K6vZRedvBJj1MfP7jK2Ma8TO0jU/EHqno9iek4ilL2Py0pfPmwL00iE0T+0oD17Lt5FHdnjxfS+qd6VTXnocQpNN9NxclHSnoQV6k2VKIzUSY1Qv07J2zzqfCWMtkQu15P/+RuOLVJfxe5gFyH94SRJZRzf1UwfsqW1L9cyaGWD9ghJpd3xnOX8u9N+Hn4TqQAXYVLNZo3oe64LdExY3xDPJ0ivk6rlDwriOueZAbwQJ5gtbfWb1bVwcpOfIz/Uve7SWtzAoDoYgAAQ8JVix2Bq8LdbDRGgZMGHVPbOF4cSc3M9vXCHb+nygjI6QZCgDGYZtwjROEm8gohbpx8EsNBFv4zQM9vyefmLFd8AAza+k7KW7QPJpaf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

