apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/cluster-install
- event-sources.yaml
- sensors.yaml
- githubcred.yaml
- sensors-rbac.yaml
namespace: argo-events
