---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: gitea
    eventSourceName: webhook
    eventName: argo-combined-app
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: argo-combined-app-
              namespace: workflows
            spec:
              entrypoint: run-e2e-tests
              serviceAccountName: workflow
              volumes:
              - name: regcred
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: github-access
                secret:
                  secretName: github-access
                  items:
                    - key: token
                      path: token
                    - key: user
                      path: user
                    - key: email
                      path: email
              templates:
                - name: run-e2e-tests
                  inputs:
                    artifacts:
                      - name: source
                        path: /src
                        git:
                          repo: git@gitea-ssh.services.svc:norge/pipeline-demo-test.git
                          revision: "HEAD"
                          insecureIgnoreHostKey: true
                          usernameSecret:
                            name: github-access-ssh
                            key: username
                          passwordSecret:
                            name: github-access-ssh
                            key: password
                          sshPrivateKeySecret:
                            name: github-access-ssh
                            key: sshPrivateKey
                  script:
                    image: cypress/included:3.4.0
                    command: [bash]
                    source: |
                      yarn install
                      npm run runHeadless
                    workingDir: /src
