---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: gitea
    eventSourceName: webhook
    eventName: argo-combined-app
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: argo-combined-app-
              namespace: workflows
            spec:
              entrypoint: run-e2e-tests
              serviceAccountName: workflow
              volumes:
              - name: regcred
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: github-access
                secret:
                  secretName: github-access
                  items:
                    - key: token
                      path: token
                    - key: user
                      path: user
                    - key: email
                      path: email
              templates:
                - name: run-e2e-tests
                  dag:
                    tasks:
                      - name: e2e-tests
                        arguments:
                          parameters:
                            - name: repository
                              value: "git@gitea-ssh.services.svc:norge/pipeline-demo-test.git"
                            - name: brach
                              value: "master"
                        templateRef:
                          name: cypress-test
                          template: run-tests
                          clusterScope: true
